[workspace]
members = [
    "crates/core",
    "crates/backend_c",
    "crates/backend_cpython",
    "crates/backend_csharp",
    "crates/proc_macros",
    "crates/reference_project",
    "examples/hello_world",
    "examples/real_project_layout/core_library",
    "examples/real_project_layout/core_library_ffi",
    "examples/real_project_layout/core_library_ffi_build",
    "examples/unity_hot_reload",
    "tests"
]
resolver = "2"

[workspace.dependencies]
derive_builder = "0.20.2"
heck = "0.5.0"
log = "0.4.14"
serde = "1.0.203"
