[package]
name = "unity_hot_reload"
version = "0.1.15"
edition = "2021"
publish = false


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
interoptopus = { path = "../../crates/core" }
interoptopus_backend_csharp = { path = "../../crates/backend_csharp" }
