[package]
name = "example_hello_world"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
interoptopus = { path = "../../interoptopus", features = ["derive"] }
interoptopus_backend_csharp = { path = "../../interoptopus_backend_csharp" }
