[package]
name = "interoptopus_backend_cpython"
description = "Generates CPython bindings."
version = "0.14.25"
edition = "2021"
license = "MIT"
keywords = ["ffi", "code-generation", "bindings", "python"]
categories = ["api-bindings", "development-tools::ffi"]
documentation = "https://docs.rs/interoptopus_backend_cpython/"
repository = "https://github.com/ralfbiedert/interoptopus"

[dependencies]
interoptopus = { path = "../core", version = "0.14.0" }
derive_builder = { workspace = true }

