[package]
name = "interoptopus_reference_project"
description = "A reference project for Interoptopus backends to test interop generation."
version = "0.1.0"
edition = "2018"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
interoptopus = { path = "../interoptopus", version = "0.1", features = ["derive"] }
