[package]
name = "example_complex"
version = "0.1.1"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
interoptopus = { path = "../../interoptopus", features = ["derive", "testing"] }

[dev-dependencies]
interoptopus_backend_csharp = { path = "../../interoptopus_backend_csharp" }
interoptopus_backend_c = { path = "../../interoptopus_backend_c" }
interoptopus_backend_cpython_cffi = { path = "../../interoptopus_backend_cpython_cffi" }
