name: Rust

on:
  push:
    branches: [ master, f/github_actions ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cffi pytest
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
